#!/usr/bin/env python3
"""Replay real multi-turn conversations (ultrachat) against a running llama-server
and measure, per turn, how a growing conversation behaves:

  - prompt_tokens and cached_tokens  -> prefix-cache hit rate (is only the new
    turn being prefilled?)
  - TTFT                             -> does first-token latency stay flat as
    history grows (cache ON) or climb (cache OFF)?
  - decode tok/s vs context depth    -> attention slows as KV fills.

The user turns come from the dataset; each assistant turn is GENERATED by the
model and appended, so the growing prefix is stable (realistic chatbot flow).

Usage: multiturn_replay.py --url URL --conversations data/ultrachat_multiturn.jsonl
        --outdir DIR --tag TAG [--n-convos 40 --max-tokens 300 --ctx 8192 --cache on]
"""
import argparse
import json
import statistics
import time
from pathlib import Path

import requests


def one_turn(base, messages, max_tokens, cache):
    payload = {"model": "qwen3-4b-legal-q6k", "messages": messages, "stream": True,
               "stream_options": {"include_usage": True}, "max_tokens": max_tokens,
               "temperature": 0.7, "cache_prompt": bool(cache)}
    t0 = time.perf_counter(); ttft = None; text = []
    ptok = ctok = cached = None; fr = None; status = None
    try:
        with requests.post(base + "/v1/chat/completions", json=payload,
                           stream=True, timeout=600) as r:
            status = r.status_code
            if r.status_code != 200:
                return None
            for raw in r.iter_lines(decode_unicode=True):
                if not raw or not raw.startswith("data:"):
                    continue
                d = raw[5:].strip()
                if d == "[DONE]":
                    break
                try:
                    o = json.loads(d)
                except json.JSONDecodeError:
                    continue
                ch = o.get("choices") or []
                if ch:
                    if (ch[0].get("delta") or {}).get("content"):
                        if ttft is None:
                            ttft = time.perf_counter() - t0
                        text.append(ch[0]["delta"]["content"])
                    if ch[0].get("finish_reason"):
                        fr = ch[0]["finish_reason"]
                if o.get("usage"):
                    ptok = o["usage"].get("prompt_tokens")
                    ctok = o["usage"].get("completion_tokens")
                    cached = (o["usage"].get("prompt_tokens_details") or {}).get("cached_tokens", 0)
    except requests.RequestException:
        return None
    dt = time.perf_counter() - t0
    if ctok is None or ttft is None:
        return None
    dec = ctok / (dt - ttft) if dt > ttft else 0.0
    return {"prompt_tokens": ptok, "cached_tokens": cached or 0, "ttft_s": ttft,
            "decode_tok_s": dec, "completion_tokens": ctok, "reply": "".join(text),
            "finish_reason": fr}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", required=True)
    ap.add_argument("--conversations", default="data/ultrachat_multiturn.jsonl")
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--tag", required=True)
    ap.add_argument("--n-convos", type=int, default=40)
    ap.add_argument("--max-tokens", type=int, default=300)
    ap.add_argument("--ctx", type=int, default=8192)     # server per-slot ctx (for the budget guard)
    ap.add_argument("--cache", default="on")
    args = ap.parse_args()
    base = args.url.rstrip("/")
    cache = args.cache.lower() in ("on", "1", "true")
    outdir = Path(args.outdir); outdir.mkdir(parents=True, exist_ok=True)

    convos = [json.loads(l) for l in open(args.conversations) if l.strip()][:args.n_convos]
    per_turn = []   # each recorded turn
    for ci, conv in enumerate(convos):
        users = [m["content"] for m in conv["messages"] if m["role"] == "user"]
        messages = []
        for ti, u in enumerate(users):
            messages.append({"role": "user", "content": u})
            res = one_turn(base, messages, args.max_tokens, cache)
            if res is None:
                break
            # stop the conversation before it would overflow the slot context
            if (res["prompt_tokens"] or 0) + args.max_tokens > args.ctx - 64:
                break
            res.update({"conv": ci, "turn": ti + 1})
            per_turn.append(res)
            messages.append({"role": "assistant", "content": res["reply"]})
        if (ci + 1) % 10 == 0:
            print(f"[replay] {ci+1}/{len(convos)} convos, {len(per_turn)} turns", flush=True)

    # write raw + aggregate by turn index and by prompt-depth bucket
    with open(outdir / f"replay-{args.tag}.jsonl", "w") as f:
        for r in per_turn:
            f.write(json.dumps({k: r[k] for k in ("conv", "turn", "prompt_tokens",
                    "cached_tokens", "ttft_s", "decode_tok_s", "completion_tokens",
                    "finish_reason")}) + "\n")

    def agg(rows):
        if not rows:
            return None
        pt = [r["prompt_tokens"] for r in rows]
        hit = [(r["cached_tokens"] / r["prompt_tokens"]) for r in rows if r["prompt_tokens"]]
        return {"n": len(rows),
                "prompt_tok_median": statistics.median(pt),
                "cache_hit_frac_median": round(statistics.median(hit), 3) if hit else None,
                "ttft_ms_median": round(1000 * statistics.median(r["ttft_s"] for r in rows), 1),
                "ttft_ms_p95": round(1000 * sorted(r["ttft_s"] for r in rows)[min(len(rows)-1, int(.95*len(rows)))], 1),
                "decode_tok_s_median": round(statistics.median(r["decode_tok_s"] for r in rows), 1)}

    by_turn = {t: agg([r for r in per_turn if r["turn"] == t]) for t in sorted({r["turn"] for r in per_turn})}
    buckets = [(0, 1000), (1000, 2000), (2000, 4000), (4000, 8000), (8000, 16000), (16000, 40000)]
    by_depth = {f"{a}-{b}": agg([r for r in per_turn if a <= (r["prompt_tokens"] or 0) < b]) for a, b in buckets}
    summary = {"tag": args.tag, "cache": cache, "server_ctx": args.ctx,
               "total_turns": len(per_turn), "by_turn": by_turn, "by_depth": by_depth}
    json.dump(summary, open(outdir / f"replay-{args.tag}.json", "w"), indent=2)
    print(f"[replay] {args.tag}: {len(per_turn)} turns | by-depth cache-hit/TTFT/decode:")
    for k, v in by_depth.items():
        if v:
            print(f"   depth {k:<12} n={v['n']:<4} cache_hit={v['cache_hit_frac_median']} "
                  f"TTFT_p50={v['ttft_ms_median']}ms decode={v['decode_tok_s_median']} tok/s")


if __name__ == "__main__":
    main()
